version: 0.0
os: linux
files:
  - source: ./home/circleci/webapp/target/demo-0.0.1-SNAPSHOT.war
    destination: /home/ubuntu/app
  - source: ./cloudwatch/cloudwatch-config.json
    destination: /opt/cloudwatch
hooks:
  AfterInstall:
    - location: ./deploycode/afterInstall.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: ./deploycode/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: ./deploycode/applicationStart.sh
      timeout: 180
      runas: ubuntu